# Generated by Django 4.1.9 on 2023-06-23 19:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        ("projects", "0003_alter_content_options_alter_project_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="content",
            name="content_type",
            field=models.ForeignKey(
                default=None,
                limit_choices_to={"model__in": ("text", "video", "image", "file")},
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="contenttypes.contenttype",
            ),
        ),
    ]
