# Generated by Django 4.1.9 on 2023-06-23 07:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='post',
            new_name='myblog Post_publish_20a94e_idx',
            old_name='blog_post_publish_493ec4_idx',
        ),
        migrations.AlterModelTable(
            name='post',
            table='myblog Post',
        ),
    ]
