# Generated by Django 4.1.9 on 2023-06-23 07:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_rename_blog_post_publish_493ec4_idx_myblog post_publish_20a94e_idx_and_more'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='post',
            new_name='blog_post_publish_493ec4_idx',
            old_name='myblog Post_publish_20a94e_idx',
        ),
        migrations.AlterModelTable(
            name='post',
            table=None,
        ),
    ]
